[custom.dataset]
annotation_path = "/path/to/WTS/environment_mcq_llava_train.py"
media_path = "/path/to/WTS/videos/train"
system_prompt = "You are a helpful assistant that can answer questions about a street-view CCTV footage."

[custom.vision]
fps = 1
max_pixels = 81920

[train]
output_dir = "outputs/wts_environment_mcq"
optm_warmup_steps = 0
train_batch_per_replica = 16
enable_validation = false

[policy]
model_name_or_path = "nvidia/Cosmos-Reason1-7B"
model_max_length = 32768

[logging]
logger = ['console', 'wandb']
project_name = "cosmos_reason1"
experiment_name = "post_training/wts_environment_mcq"

[train.train_policy]
type = "sft"
mini_batch = 1
dataset.test_size = 0

[train.ckpt]
enable_checkpoint = true

[policy.parallelism]
tp_size = 1
cp_size = 1
dp_shard_size = 8
pp_size = 1
